apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - port: 3001
  selector:
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: muhammedrashi/auth-service:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: app-config
