apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  ports:
    - port: 3003
  selector:
    app: driver-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  selector:
    matchLabels:
      app: driver-service
  replicas: 1
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: muhammedrashi/driver-service:latest
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: app-config
