apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 3002
  selector:
    app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: muhammedrashi/user-service:latest
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: app-config
